---
name: Posy-Plugin-Toc
version: 0.5501
author:
  - Kathryn Andersen
abstract: Posy plugin create a table of contents.
license: perl
requires:
  Posy: 0.95
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::Toc:
    file: lib/Posy/Plugin/Toc.pm
    version: 0.5501
generated_by: Module::Build version 0.261
